### ISSUE TITLE
Use the MODULE.bazel version string and avoid hardcoding it into build.rs files.

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput-rs#74]
## Desired behavior

Avoid this:

https://github.com/maliput/maliput-rs/blob/76ad45a1da4aba55c2d028ab542c3530657df75f/maliput-sdk/build.rs#L60-L61

by reading the MODULE.bazel file and scrapping the version.

## Alternatives considered
- Consider looking for a variable in the file.
- Make query to bazel (mod) and get the package and version. 

## Implementation suggestion

N/A

## Additional context
N/A

**Comment by francocipollone** [comment]
@agalbachicar 

Sending some aid:  
```
bazel mod graph | grep -oP 'maliput@\K[\d.]+'
bazel mod graph | grep -oP 'maliput_malidrive@\K[\d.]+'
```
